Added MDK4 for Termux
termux/termux-root-packages pull request #236
Opened 2021-04-14 14:41 UTC by gitdebpro

added a new package called MDK4 tested on armhf but not on arm64 due to lack of device availability.

2021-04-14 17:33 UTC, gitdebpro commented
Hi there attaching mdk4 build script with all patches and also already build mdk4.deb for armhf only. Just extract the zip.
[mdk4.zip](https://github.com/termux/termux-root-packages/files/6312659/mdk4.zip)

2021-04-16 07:46 UTC, Grimler91 requested changes
See comments

2021-04-16 07:46 UTC, Grimler91 commented on packages/mdk4/build.sh
> +#MDK is a proof-of-concept tool to exploit common IEEE 802.11 protocol weaknesses.
Remove all of these comments

2021-04-16 07:46 UTC, Grimler91 commented on packages/mdk4/build.sh
> +TERMUX_PKG_MAINTAINER="KimoCoder & Ezmer "
Are you Kimocoder or Ezmer? 

If not then set it you yourself or @termux. It should be the person responsible for the package in the termux repositories.

2021-04-16 07:46 UTC, Grimler91 commented on packages/mdk4/build.sh
> +
Remove extra empty lines

2021-04-16 07:46 UTC, Grimler91 commented on packages/mdk4/build.sh
> +TERMUX_PKG_REVISION=1
Remove this line, it does not have to be set for new packages

2021-04-16 07:46 UTC, Grimler91 commented on packages/mdk4/build.sh
> +TERMUX_PKG_SRCURL=https://github.com/aircrack-ng/mdk4/archive/master.zip
Don't use master.zip. Build from a tagged release or a specific commit

2021-04-16 07:46 UTC, Grimler91 commented on packages/mdk4/build.sh
> +TERMUX_PKG_DEPENDS="aircrack-ng, pkg-config, libnl, libpcap"
Remove pkg-config. It is not a runtime dependency

2021-04-16 07:46 UTC, Grimler91 commented on packages/mdk4/build.sh
> +TERMUX_PKG_BUILD_IN_SRC=true
Have you tried building out of source, i.e. without this line?

2021-04-16 07:46 UTC, Grimler91 commented on packages/mdk4/build.sh
> +
Remove the extra empty line here

2021-04-16 07:57 UTC, gitdebpro commented on packages/mdk4/build.sh
> +#MDK is a proof-of-concept tool to exploit common IEEE 802.11 protocol weaknesses.
ok will do that

2021-04-16 08:00 UTC, gitdebpro commented on packages/mdk4/build.sh
> +TERMUX_PKG_BUILD_IN_SRC=true
no i didn't try that

2021-04-16 08:23 UTC, Grimler91 commented on packages/mdk4/build.sh
> +TERMUX_PKG_BUILD_IN_SRC=true
Please try it. This option should only be set if it is required

2021-04-16 08:36 UTC, gitdebpro commented on packages/mdk4/build.sh
> +#MDK is a proof-of-concept tool to exploit common IEEE 802.11 protocol weaknesses.
removed

2021-04-16 08:36 UTC, gitdebpro commented on packages/mdk4/build.sh
> +TERMUX_PKG_MAINTAINER="KimoCoder & Ezmer "
used @termux

2021-04-16 08:36 UTC, gitdebpro commented on packages/mdk4/build.sh
> +
removed

2021-04-16 08:37 UTC, gitdebpro commented on packages/mdk4/build.sh
> +TERMUX_PKG_REVISION=1
without these lines there are build error so kept these lines but turned the value empty

2021-04-16 08:51 UTC, Grimler91 commented on packages/mdk4/build.sh
> +TERMUX_PKG_REVISION=1
TERMUX_PKG_VERSION=4.1 needs to be there. TERMUX_PKG_REVISION=1 can be removed

2021-04-16 08:54 UTC, gitdebpro commented on packages/mdk4/build.sh
> +TERMUX_PKG_REVISION=1
ok got it will do that

2021-04-16 17:19 UTC, gitdebpro commented on packages/mdk4/build.sh
> +TERMUX_PKG_REVISION=1
removing the line TERMUX_PKG_REVISION=1 stops the build process but keeping its value empty dosent affect the build process so I kept it empty and also tested arm and aarch64 both developed correctly

2021-04-16 17:20 UTC, gitdebpro commented on packages/mdk4/build.sh
> +TERMUX_PKG_SRCURL=https://github.com/aircrack-ng/mdk4/archive/master.zip
changed to commit fc03b0ece893fd8d3f546d915511f01ba3faebc8.zip

2021-04-16 17:20 UTC, gitdebpro commented on packages/mdk4/build.sh
> +TERMUX_PKG_DEPENDS="aircrack-ng, pkg-config, libnl, libpcap"
removed

2021-04-16 17:20 UTC, gitdebpro commented on packages/mdk4/build.sh
> +TERMUX_PKG_BUILD_IN_SRC=true
tried without these lines but error in build process

2021-04-16 17:20 UTC, gitdebpro commented on packages/mdk4/build.sh
> +
removed

2021-04-16 17:23 UTC, gitdebpro commented
Finally completed all changes as requested and tested on both arm and aarch64 , both completed and created respective .deb files successfully

2021-04-17 05:13 UTC, gitdebpro commented
@Grimler91 I just want to know if accepted, when this package will be available at termux package repo i mean when it will show inside termux like 

apt-cache search mdk4 will show it.

Regards.

2021-04-17 08:42 UTC, Grimler91 requested changes

2021-04-17 08:42 UTC, Grimler91 commented on packages/mdk4/build.sh
> +TERMUX_PKG_REVISION=
Remove this line completely, no need to set it

2021-04-17 10:59 UTC, Grimler91 commented
@gitdebpro it should be available on all mirrors within a few hours after adding it

2021-04-17 12:16 UTC, gitdebpro commented on packages/mdk4/build.sh
> +TERMUX_PKG_REVISION=
removed done.

2021-04-17 12:29 UTC, gitdebpro commented
I have made all the suggested changes now I guess there is no problem.

Regards

2021-04-17 13:24 UTC, Grimler91 commented
Great, thanks for the PR!

2021-04-17 13:24 UTC, merged